
["Zombie Equipment"]
	#Items / chance of spawning with it
	"Head Slot" = ["minecraft:chainmail_helmet|50", "minecraft:iron_helmet|20", "minecraft:leather_helmet|20"]
	"Chest Slot" = ["minecraft:chainmail_chestplate|50", "minecraft:iron_chestplate|20", "minecraft:leather_chestplate|20"]
	"Main Hand Slot" = ["minecraft:stone_sword|50", "minecraft:iron_sword|20", "minecraft:golden_pickaxe|15", "minecraft:iron_pickaxe|20", "minecraft:golden_sword|30"]
	"Legs Slot" = ["minecraft:leather_leggings|50", "minecraft:iron_leggings|20", "minecraft:chainmail_leggings|20"]
	"Boots Slot" = ["minecraft:leather_boots|50", "minecraft:iron_boots|20", "minecraft:chainmail_boots|20"]
	"Off Hand Slot" = ["minecraft:ender_pearl|15", "minecraft:totem_of_undying|10", "minecraft:spyglass|20", "minecraft:shield|30", "minecraft:flint_and_steel|30"]
	#Default true
	"Should zombies spawn with more armor and tools and more commonly" = true
	#Default 160
	"Chance of the zombies spawning with improved equipment, the bigger the number the smaller the chance" = 160

